server:
  port: 80
security:
  basic:
    enabled: false

spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/activiti522?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

logging.level.org.activiti.engine.impl.persistence.entity: debug
